grpc:
  server:
    port: 9090
    address: 0.0.0.0  # Optional

#logging:
#  level:
#    io.grpc: DEBUG
#    org.springframework: DEBUG
#    com.matin.happychat: DEBUG
#    io.grpc.netty: DEBUG
#    io.grpc.stub: DEBUG
#    io.grpc.internal: DEBUG
#    io.grpc.ServerImpl: DEBUG
